# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.product.service:
        class:   AppBundle\Service\ProductService
        arguments: ['@doctrine.orm.default_entity_manager','@service_container']
    app.category.service:
        class:   AppBundle\Service\CategoryService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.producer.service:
        class:   AppBundle\Service\ProducerService
        arguments: ['@doctrine.orm.default_entity_manager']
